Completed issue #10 Build training page hero
tcet-opensource/tnp-website pull request #13
Opened 2023-04-07 09:38 UTC by adityayadav71

1. Created training.astro file in pages.
2. Created TrainingHero.tsx and TrainingHeroCarousel.tsx components.
3. Added styles.css file to support custom swiper navigation buttons.
4. Added relevant image and icon resources in public folder.

2023-04-08 14:40 UTC, demonkillerr reviewed
code looks good to me

2023-04-08 14:44 UTC, vish-rt reviewed
LGTM

2023-04-09 13:20 UTC, demonkillerr submitted a review, later dismissed
please go through image optimization guides in resources' tab and make changes as request by @JayeshVP24

2023-04-09 13:21 UTC, JayeshVP24 requested changes

2023-04-09 13:21 UTC, JayeshVP24 commented on public/book-open.svg
move svgs to misc folder

2023-04-09 13:21 UTC, JayeshVP24 commented on public/student-workshop.png
move to events folder in public dir

2023-04-09 13:21 UTC, JayeshVP24 commented on src/components/TrainingHeroCarousel.tsx
> +        <img src="/student-workshop.png" alt="student-workshop" className="h-full w-auto object-cover rounded-xl" />
use `<Image>` tag of @astro everywhere

2023-04-10 16:12 UTC, riyavishwa981 approved these changes

2023-04-11 12:06 UTC, JayeshVP24 approved these changes

2023-04-11 12:07 UTC, merged