11 build prof bodies open source title huge events
tcet-opensource/tnp-website pull request #15
Opened 2023-04-08 14:44 UTC by riyavishwa981

2023-04-08 14:59 UTC, demonkillerr reviewed
code looks good to me

2023-04-09 13:17 UTC, JayeshVP24 requested changes

2023-04-09 13:17 UTC, JayeshVP24 commented on src/components/ProfessionalBodies.jsx
> +                <img
use `<Image>` tag of @astro/image/components

2023-04-09 13:17 UTC, JayeshVP24 commented on public/imgs/tcet_shastra.png
rename images folder to logos

2023-04-09 13:17 UTC, JayeshVP24 commented on public/imgs/pic_1.png
move to events folder

2023-04-09 13:17 UTC, JayeshVP24 commented on public/imgs/astronaut.png
move to folder misc

2023-04-11 19:32 UTC, JayeshVP24 approved these changes

2023-04-11 19:32 UTC, merged