6 build top recruiters
tcet-opensource/tnp-website pull request #17
Opened 2023-04-09 12:13 UTC by ShudhanshuSingh

Changes Implemented as per discussion with @JayeshVP24 and @riyavishwa981 on discord.
=> Added Foggy Borders
=> Marquee Added
=> Mobile responsive

2023-04-09 13:17 UTC, demonkillerr submitted a review, later dismissed
please go through image optimization guides in resources' tab and make changes as request by @JayeshVP24

2023-04-09 13:18 UTC, JayeshVP24 requested changes

2023-04-09 13:18 UTC, JayeshVP24 commented on src/components/TopRecruiters.jsx
> +            <img className="h-8 object-contain mt-5" src={imgUrl} alt="random" />
use `<Image>` tag of @astro/image/components
Everywhere..

2023-04-10 15:59 UTC, JayeshVP24 approved these changes
Ready to merge

2023-04-10 16:16 UTC, riyavishwa981 approved these changes

2023-04-10 16:19 UTC, merged