[MAJOR] Index, training, internship, about pages ready!!
tcet-opensource/tnp-website pull request #39
Opened 2023-04-15 16:18 UTC by JayeshVP24

2023-04-15 17:09 UTC, demonkillerr requested changes
Kindly make the following changes

1. Following changes are global

    - [ ] Route the links correctly to training, internship and [open source](https://opensource.tcetmumbai.in/) pages
    - [ ] Fix spelling mistakes through out the website
    - [ ] Add primary navbar links
    - [ ] Add Favicon
    - [ ] Add About to PR title

2. Training Page

    - [ ] Replace Hacknova with Solving for India GFG hackathon
    - [ ] Replace CC with GFG event

3. About Page

    - [ ] Submit button should work (mailto)

4. Internship Page

    - [ ] Fix no of students for larger screens

2023-04-15 17:51 UTC, riyavishwa981 commented
For Landing Page
1. make some space between view more and the image below it 
![image](https://user-images.githubusercontent.com/79577834/232244944-477db975-16f0-4954-95d5-4155774f9c3c.png)
2. When changing the screen for mobile, make sure its properly responsive
![image](https://user-images.githubusercontent.com/79577834/232245191-8b595410-ba1f-41fa-bb95-404e891b0855.png)
![image](https://user-images.githubusercontent.com/79577834/232245233-62521e5a-f381-40be-a26a-4ee77c44862f.png)
![image](https://user-images.githubusercontent.com/79577834/232245250-1df9614b-0dd0-40ec-80dc-a4611079e698.png)

2023-04-15 23:00 UTC, demonkillerr commented
Res: 1920x1080
![image](https://user-images.githubusercontent.com/55846983/232256594-5aa3b880-25be-4091-a47e-5c11f647310e.png)

2023-04-15 23:01 UTC, demonkillerr commented
Add `target=_blank` on all external links

2023-04-17 06:33 UTC, riyavishwa981 approved these changes

2023-04-18 20:03 UTC, demonkillerr requested changes

2023-04-18 20:03 UTC, demonkillerr commented on src/pages/index.astro
> +  description="The official Website of Training and Placement Cell of the amazing Thakur College of Engineering and Technology"
need to revert this

2023-04-18 20:07 UTC, demonkillerr requested changes
Important Change:

- [ ] Replace all dummy text with actual text
- [ ] Replace all dummy images with real images

2023-04-25 17:11 UTC, JayeshVP24 commented
Ready to merge

2023-04-25 17:27 UTC, vish-rt approved these changes
Looks good to me!

2023-04-25 17:33 UTC, demonkillerr approved these changes

2023-04-25 17:35 UTC, demonkillerr approved these changes

2023-04-25 17:39 UTC, merged

2023-04-25 17:39 UTC, demonkillerr commented
Final Production Push for TNP Website. End of beta-testing phase.

Website can be accessed at [https://tnp.tcetmumbai.in/](https://tnp.tcetmumbai.in/).