CONTRIBUTERS.md file is added
tcet-opensource/tnp-website pull request #56
Opened 2023-04-27 05:55 UTC by Wmg20

2023-04-27 14:52 UTC, demonkillerr commented
Kindly mention the issue number.

2023-04-27 14:54 UTC, demonkillerr requested changes

2023-04-27 14:54 UTC, demonkillerr commented on CONTRIBUTERS.md
> +- [VedantPol] (https://github.com/VedantPol)
Kindly check the spacing. I recommend that we keep it consistent throughout.

2023-04-27 14:54 UTC, demonkillerr commented
@kuxshl kindly mention the UI/UX team members responsible for the design.

2023-04-27 15:09 UTC, kuxshl commented
UI/UX Team for this project:

@kuxshl 
@Mahitej28 
@SwanshTCET 
@JayeshVP24

2023-04-27 15:50 UTC, Wmg20 commented on CONTRIBUTERS.md
> +- [VedantPol] (https://github.com/VedantPol)
okay, I will fix it

2023-04-27 16:03 UTC, Wmg20 reviewed
done

2023-05-02 18:55 UTC, demonkillerr approved these changes
Looks Good to me.

2023-05-02 19:02 UTC, riyavishwa981 approved these changes

2023-05-02 19:03 UTC, merged