[ADDED]Getting Started
tcet-opensource/tnp-website pull request #79
Opened 2023-09-14 16:18 UTC by tanishakumar18

Added Getting started for TNP Website

2023-09-14 17:14 UTC, kamalika0363 commented
[ADDED] #78   
README for TnP Website

2023-09-14 18:06 UTC, vish-rt requested changes
Recommend having a look at the suggestions and make new commits to your fork.

2023-09-14 18:06 UTC, vish-rt commented on Getting started.md
The content of this file should be in `README.md` only. Putting this in any other file would not reflect within the repository's description.
- [ ] Copy everything written in this file
- [ ] Replace the contents of `README.md` with this

2023-09-14 18:06 UTC, vish-rt commented on Getting started.md
> +**Info:**
While writing a project's description, always begin with the project's name. Leverage heading tags (#) to highlight them.

2023-09-16 10:12 UTC, vish-rt approved these changes
Great!

2023-09-16 10:12 UTC, merged